Changes to per bug/NIOS-84401
infobloxopen/infoblox-client pull request #334
Opened 2022-07-20 15:55 UTC by sarya-infoblox

# Issue/Feature description

* Update operation updates the objects by excluding non-updatable fields

# How it was fixed/implemented

* Added the Logs where non-updatable fields are skipped.

2022-07-25 17:58 UTC, achernevskii requested changes

2022-07-25 17:58 UTC, achernevskii commented on infoblox_client/objects.py
> +            fields = [field for field in self._fields if field not in update_fields]
```suggestion
            fields = [field for field in self._fields 
                      if field not in update_fields]
```

2022-07-25 17:58 UTC, achernevskii commented on infoblox_client/objects.py
> +            LOG.info("Field is not allowed for update: %s - ignoring" % key)
Please don't format log messages when calling log methods. Instead pass the format message and parameters as log method arguments, like this:
```suggestion
            LOG.info(
                "Field is not allowed for update: %s - ignoring",
                key,
            )
```

This is called lazy logging. This way, your message will be formatted only if the log level is `info`, or more verbose.

2022-07-28 06:18 UTC, ranjishmp approved these changes

2022-07-28 14:20 UTC, achernevskii approved these changes

2022-08-22 07:25 UTC, merged